fix: Correct schema item names in local_admin_password_settings resource (#667)
Correct schema item names in local_admin_password_settings resource

Noticed the previous (sans `_seconds`) names were in use. This was causing the plugin to crash:

```
goroutine 138 [running]:
github.com/deploymenttheory/terraform-provider-jamfpro/internal/resources/localadminpasswordsettings.constructLocalAdminPasswordSettings(0x140001add00)
        github.com/deploymenttheory/terraform-provider-jamfpro/internal/resources/localadminpasswordsettings/constructor.go:21 +0x234
github.com/deploymenttheory/terraform-provider-jamfpro/internal/resources/localadminpasswordsettings.create({0x101f765d8, 0x1400025aa80}, 0x140001add00, {0x101f555e0, 0x1400007eac8})
        github.com/deploymenttheory/terraform-provider-jamfpro/internal/resources/localadminpasswordsettings/crud.go:18 +0x54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400016e800, {0x101f76530, 0x140005fd7d0}, 0x140001add00, {0x101f555e0, 0x1400007eac8})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:838 +0xe4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400016e800, {0x101f76530, 0x140005fd7d0}, 0x14000794340, 0x140001adb80, {0x101f555e0, 0x1400007eac8})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:969 +0x874
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400048c378, {0x101f76530?, 0x140005fd710?}, 0x140007865a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/grpc_provider.go:1188 +0xaa4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140002cae60, {0x101f76530?, 0x140005fcc90?}, 0x1400025a380)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/tf5server/server.go:866 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x101f1e520, 0x140002cae60}, {0x101f76530, 0x140005fcc90}, 0x140001ad300, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000112000, {0x101f76530, 0x140005fcc30}, 0x1400001c6c0, 0x1400021d6e0, 0x1028fe698, 0x0)
        google.golang.org/grpc@v1.69.4/server.go:1392 +0xc44
google.golang.org/grpc.(*Server).handleStream(0x14000112000, {0x101f774a0, 0x14000270b60}, 0x1400001c6c0)
        google.golang.org/grpc@v1.69.4/server.go:1802 +0x910
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.69.4/server.go:1030 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 27
        google.golang.org/grpc@v1.69.4/server.go:1041 +0x13c

Error: The terraform-provider-jamfpro_v0.18.0 plugin crashed!
```

Hopefully this should sort. :-)